services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5051:80"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
  bsn-api:
    container_name: bsn-api
    image: bsn/bsn:1.0.1
    ports:
      - "8088:8088"
    networks:
      - spring-demo
    depends_on:
      - postgres

  bsn-ui:
    container_name: bsn-ui
    image: bsn/bsn-ui:1.0.0
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api


networks:
  spring-demo:
    driver: bridge


volumes:
  postgres:
    driver: local
  pgadmin: