  spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/book_social_network
      username: username
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    mail:
      host: smtp.gmail.com
      port: 465
      username: username
      password: password
      properties:
        mail:
          smtp:
            auth: true
            ssl:
              enable: true
              trust: "*"
          starttls:
            enabled: true
      protocol: smtp
  application:
    security:
      jwt:
        secret-key: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
        expiration: 8640000
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account
    file:
      upload:
        photos-output-path: ./uploads
  server:
    port: 8088